-- ============================================================
-- 02_patch.sql  (2026-05-11)
-- 174건 PATCH — 엑셀 임대현황.xlsx 기준 (PATCH 모드)
--   덮어쓰기 필드: base_fee/company/address/bw_*/co_*/source_sheet
--   memo: 엑셀 비고가 새 정보면 append, 기존 memo 보존
-- ============================================================
BEGIN;

UPDATE rental_customers SET company = '수성2,3가 새마을금고 (본점:1/지점:1)', source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0000';
UPDATE rental_customers SET base_fee = 35000, bw_free = 500, source_sheet = '임대현황.xlsx', memo = E'임대기기: 교세라 3212i\n임대일: 2017.05.02\n2020.05.02\n제품구성: 흑백복사기1\n선후불/보증금: 선불 / 20만\n추가장당: 흑:3,000매(10원)\n청구일: 5일\n입금일: 5일 렌탈마니\n비고: 21.2.5 금액할인 10->7만\n6525->3212i 제품교체(230327)\n\n[2026-05-11 임대현황.xlsx 비고]\n21.2.5 금액할인 10->7만     / 6525->3212i 제품교체(230327)\n금액할인 7->3.5 : 26.05.11', updated_at = NOW() WHERE id = 'c_0001';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0002';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0003';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0004';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0005';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0007';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0009';
UPDATE rental_customers SET base_fee = 95000, address = '성주군 성주읍 성주산업단지로5길 83', source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0290';
UPDATE rental_customers SET base_fee = 245000, source_sheet = '임대현황.xlsx', memo = E'임대기기: 교세라 251ci\n임대일: 2020.01.01\n2020.12.31\n제품구성: 흑백복사기1\n선후불/보증금: 선불 / 1년계약\n추가장당: 흑 무제한\n청구일: 1년\n비고: 2019.05.09 신규설치\n\n[2026-05-11 임대현황.xlsx 비고]\n17.12.28 6025->3051교체\n22.15.05. 5910-> T925 교체\n2019.05.09 신규설치', updated_at = NOW() WHERE id = 'c_0016';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0014';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0018';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0019';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0021';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0025';
UPDATE rental_customers SET base_fee = 100000, address = '달서구 파호동 202-1', source_sheet = '임대현황.xlsx', memo = E'[무상임대현황]\n임대기기: 교세라FS-1120D\n비고: 무상 임대 · 17.06.12 1110 ->1120으로 교체\n\n[2026-05-11 임대현황.xlsx 비고]\n2018.10.11\n24.05.30 : 2552->2554', updated_at = NOW() WHERE id = 'c_0306';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0029';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0030';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0033';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0034';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0035';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0036';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0037';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0038';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0039';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0040';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0043';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0046';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0047';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0048';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0050';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0051';
UPDATE rental_customers SET bw_free = 999999, source_sheet = '임대현황.xlsx', memo = E'임대기기: 교세라 2554ci+팩스\n임대일: 16.04.25\n제품구성: 컬러복사기1\n선후불/보증금: 선불 / 없음\n추가장당: 흑백:무제한\n컬러:판매조건\n청구일: 25일\n입금일: 25일 렌탈마니\n비고: 제품교체 2554ci : 230829\n\n[2026-05-11 임대현황.xlsx 비고]\n제품교체 2554ci : 230829\n고덱스 G500 추가 : 26.05.11', updated_at = NOW() WHERE id = 'c_0053';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0054';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0055';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0056';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0057';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0059';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0060';
UPDATE rental_customers SET base_fee = 115000, source_sheet = '임대현황.xlsx', memo = E'임대기기: 브라더 L5100DN(현장)\n임대일: 2023.01.16\n제품구성: 레이저1\n선후불/보증금: 후불 / 없음\n청구일: 25일\n입금일: 20일입금\n\n[2026-05-11 임대현황.xlsx 비고]\n21.05.14 3010->3212교체\n25.06.25 : 이외 제품 회수, 계약서 수정', updated_at = NOW() WHERE id = 'c_0067';
UPDATE rental_customers SET base_fee = 290000, source_sheet = '임대현황.xlsx', memo = E'임대기기: 브라더 J2740dw(2공장)\n임대일: 24.12.29\n제품구성: 잉크젯1\n선후불/보증금: 선불 / 없음\n청구일: 25일\n입금일: 말일\n\n[2026-05-11 임대현황.xlsx 비고]\n22.11.24(2720->2740 교체)\n21.06.15(6525->3212i 교체)', updated_at = NOW() WHERE id = 'c_0070';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0071';
UPDATE rental_customers SET base_fee = 356364, source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0073';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0074';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0075';
UPDATE rental_customers SET bw_free = 2000, bw_rate = 10, source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0078';
UPDATE rental_customers SET bw_free = 2000, bw_rate = 10, source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0079';
UPDATE rental_customers SET bw_free = 1000, bw_rate = 10, source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0080';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0081';
UPDATE rental_customers SET bw_free = 999999, source_sheet = '임대현황.xlsx', memo = E'임대기기: 교세라2552ci\n임대일: 17.03.30\n20.03.30\n제품구성: 컬러복사기1\n선후불/보증금: 선불 / 없음\n추가장당: 흑백:무제한\n컬1,000장(150원)\n청구일: 30일\n입금일: 입금\n\n[2026-05-11 임대현황.xlsx 비고]\n17.07.20 HL-2365->1120으로 교체', updated_at = NOW() WHERE id = 'c_0082';
UPDATE rental_customers SET bw_free = 999999, source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0083';
UPDATE rental_customers SET bw_free = 999999, source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0084';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0085';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0093';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0094';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0097';
UPDATE rental_customers SET bw_free = 3, source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0098';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0100';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0101';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0103';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0106';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0108';
UPDATE rental_customers SET base_fee = 30000, address = '달서구 호림동 9-6
모다지식산업센터 다동101호', source_sheet = '임대현황.xlsx', memo = E'[무상임대현황]\n임대기기: HP LJ1020 (1대)\n임대일: 10.12.30\n비고: 무상 임대 ·\n\n[2026-05-11 임대현황.xlsx 비고]\n1020->M2070 교체(21.06.14)무상', updated_at = NOW() WHERE id = 'c_0279';
UPDATE rental_customers SET bw_free = 1, co_free = 1000, source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0114';
UPDATE rental_customers SET base_fee = 50000, address = '대구 달성군 세천로 1길 116-1번지', bw_free = 1000, bw_rate = 10, source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0272';
UPDATE rental_customers SET base_fee = 140000, address = '달서구 월암동 929-8', source_sheet = '임대현황.xlsx', memo = E'[무상임대현황]\n임대기기: 브라더MFC-2700\n임대일: 15.08.10\n비고: 무상 임대 · 17.03.29 7360->2700으로 교체\n\n[2026-05-11 임대현황.xlsx 비고]\n21.03.15부터 154,000원 세금계산서 발행', updated_at = NOW() WHERE id = 'c_0298';
UPDATE rental_customers SET address = '달서구 갈산동 100-23', source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0301';
UPDATE rental_customers SET address = '달서구 갈산동 985-5 
유통단지 73호', source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0304';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0121';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0122';
UPDATE rental_customers SET bw_free = 3, source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0124';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0125';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0127';
UPDATE rental_customers SET company = '송원이앤지 송원ENG', co_free = 1000, co_rate = 100, source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0128';
UPDATE rental_customers SET base_fee = 225000, source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0130';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0131';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0132';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0133';
UPDATE rental_customers SET bw_free = 3, co_free = 300, source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0134';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0136';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0141';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0145';
UPDATE rental_customers SET bw_free = 1, source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0146';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0148';
UPDATE rental_customers SET bw_free = 500, bw_rate = 10, source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0149';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0150';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0151';
UPDATE rental_customers SET bw_free = 2000, bw_rate = 10, source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0154';
UPDATE rental_customers SET bw_free = 5000, bw_rate = 10, co_free = 2000, co_rate = 100, source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0155';
UPDATE rental_customers SET bw_free = 3000, bw_rate = 10, co_free = 1000, co_rate = 50, source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0157';
UPDATE rental_customers SET bw_free = 1, co_free = 500, co_rate = 100, source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0159';
UPDATE rental_customers SET bw_free = 1, co_free = 500, co_rate = 100, source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0160';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0161';
UPDATE rental_customers SET co_free = 1000, co_rate = 100, source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0162';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0165';
UPDATE rental_customers SET company = '두일전기 (전, 대동솔루션)', co_free = 200, co_rate = 100, source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0166';
UPDATE rental_customers SET co_free = 500, co_rate = 100, source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0167';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0169';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0170';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0171';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0172';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0176';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0177';
UPDATE rental_customers SET co_free = 500, co_rate = 100, source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0179';
UPDATE rental_customers SET co_free = 1000, co_rate = 80, source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0181';
UPDATE rental_customers SET base_fee = 150000, address = '대구 수성구 알파시티1로 275 (대흥동)
알파시티 롯데뷰 3층', co_free = 1000, co_rate = 100, source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0183';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0187';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0188';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0190';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0191';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0192';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0193';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0194';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0195';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0196';
UPDATE rental_customers SET base_fee = 140000, address = '대구 달서구 달구벌대로307길 11 201호', source_sheet = '임대현황.xlsx', memo = E'[BNI]\n임대기기: 조립 i3-13100/16G/512G(3만) : 1대\n모니터 24인치 : 2대(5천*2)\n교세라 5526cdn (6만)\n임대일: 23.10.20\n비고: BNI · 장준석\n\n[2026-05-11 임대현황.xlsx 비고]\n25.03월부터 임대료 변경 (8->10)\n25.09.08 브라더5700 설치', updated_at = NOW() WHERE id = 'c_0308';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0199';
UPDATE rental_customers SET company = '더함수학교습소 우리모습보존회', source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0200';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0201';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0203';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0204';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0206';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0207';
UPDATE rental_customers SET bw_free = 10, co_free = 100, source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0208';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0210';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0211';
UPDATE rental_customers SET base_fee = 68000, address = '대구 수성구 범어천로 167 5층', source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0310';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0213';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0215';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0216';
UPDATE rental_customers SET bw_free = 10, co_free = 100, source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0217';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0219';
UPDATE rental_customers SET base_fee = 130000, address = '대구 달서구 달서대로58길 84, 1층', bw_free = 1000, bw_rate = 10, co_free = 700, co_rate = 100, source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0311';
UPDATE rental_customers SET co_free = 1000, co_rate = 100, source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0222';
UPDATE rental_customers SET base_fee = 110000, company = '대한바디솔루션협회 (김동겸)', address = '대구 수성구 동대구로 149
경북 구미시 문화로 50,2층(원평동)', source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0312';
UPDATE rental_customers SET base_fee = 80000, address = '대구 동구 화랑로 377 2층', source_sheet = '임대현황.xlsx', memo = E'[BNI]\n임대기기: 조립 i3-14100/16G/500G : 1대(2.5만)\n유디아모니터 24인치 : 1대(5천)\n임대일: 24.09.03\n비고: BNI · 김혜선\n\n[2026-05-11 임대현황.xlsx 비고]\n25.06.16. 5526 1대 추가 / 7월부터 청구함', updated_at = NOW() WHERE id = 'c_0313';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0225';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0226';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0229';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0231';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0232';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0233';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0235';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0236';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0237';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0238';
UPDATE rental_customers SET co_free = 500, co_rate = 100, source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0239';
UPDATE rental_customers SET co_free = 500, co_rate = 100, source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0240';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0241';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0242';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0243';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0244';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0246';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0247';
UPDATE rental_customers SET address = '대구광역시 북구 태암로 18길 28', bw_free = 500, bw_rate = 10, co_free = 500, co_rate = 100, source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0317';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0249';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0252';
UPDATE rental_customers SET co_free = 100, co_rate = 100, source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0253';
UPDATE rental_customers SET bw_free = 10, co_free = 100, source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0254';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0255';
UPDATE rental_customers SET bw_free = 3000, bw_rate = 10, source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0256';
UPDATE rental_customers SET co_free = 500, co_rate = 50, source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0257';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0258';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0259';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0261';
UPDATE rental_customers SET co_free = 500, co_rate = 50, source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0262';
UPDATE rental_customers SET co_free = 3000, co_rate = 20, source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0263';
UPDATE rental_customers SET company = '민텍스 (민테크)', co_free = 400, co_rate = 100, source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0264';
UPDATE rental_customers SET co_free = 500, co_rate = 100, source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0265';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0266';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0267';
UPDATE rental_customers SET co_free = 500, co_rate = 100, source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0268';
UPDATE rental_customers SET source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0270';
UPDATE rental_customers SET co_free = 5000, co_rate = 20, source_sheet = '임대현황.xlsx', updated_at = NOW() WHERE id = 'c_0271';

-- 총 174건 PATCH, memo append: 11건
COMMIT;

-- 검증
SELECT COUNT(*) AS patched_today
  FROM rental_customers
 WHERE source_sheet = '임대현황.xlsx'
   AND updated_at >= NOW() - INTERVAL '5 minutes';