-- ============================================================
-- 15_seed_counters.sql  (auto-generated)
-- data/월별카운터/*/한별카운터_*.xlsx → rental_counters + serial UPDATE
-- 매칭: rental_customers.company × rental_items.model 토큰
-- ============================================================

-- ---- rental_items.serial 보강 ----
UPDATE rental_items SET serial='VUV2620312' WHERE id='it_0150' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='VUV4Z30079' WHERE id='it_0253' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='VUV4Z30077' WHERE id='it_0242' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='VUV5530904' WHERE id='it_0153' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='W8M2Z00153' WHERE id='it_0091' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='18Y3400305' WHERE id='it_0015' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='WB85202852' WHERE id='it_0080' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='RPT1104225' WHERE id='it_0151' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='REH1408061' WHERE id='it_0064' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='VUV2319293' WHERE id='it_0144' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='VP97200426' WHERE id='it_0081' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='RPT9300292' WHERE id='it_0079' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='REH9102528' WHERE id='it_0060' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='WB85303067' WHERE id='it_0260' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='18Y3300014' WHERE id='it_0203' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='VP98303260' WHERE id='it_0046' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='18Z3400260' WHERE id='it_0196' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='WC73700480' WHERE id='it_0047' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='REH8901018' WHERE id='it_0116' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='VUV4Z29638' WHERE id='it_0241' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='RPS2104956' WHERE id='it_0159' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='VUV1816191' WHERE id='it_0155' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='VUV7Z00809' WHERE id='it_0164' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='W8M2Z00209' WHERE id='it_0209' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='RPT1805259' WHERE id='it_0165' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='VUV4Z29498' WHERE id='it_0136' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='LV25Y05283' WHERE id='it_0089' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='VUV0110808' WHERE id='it_0130' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='VUV1615726' WHERE id='it_0152' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='RPT0Z03830' WHERE id='it_0050' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='RPT2307260' WHERE id='it_0092' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='RPT0Z03838' WHERE id='it_0025' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='WB82500540' WHERE id='it_0016' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='RPT0602467' WHERE id='it_0217' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='WC73600352' WHERE id='it_0096' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='WC72Y00144' WHERE id='it_0070' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='WB85X04018' WHERE id='it_0278' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='VUV2319297' WHERE id='it_0126' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='VP98Y04684' WHERE id='it_0074' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='RPT0Z03826' WHERE id='it_0075' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='VUV3Z27062' WHERE id='it_0202' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='WB85303073' WHERE id='it_0263' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='REH0Y07264' WHERE id='it_0108' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='RPT0Z03837' WHERE id='it_0145' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='RPT0Z03822' WHERE id='it_0149' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='W8M2Z00154' WHERE id='it_0234' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='18Y3400245' WHERE id='it_0030' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='WB82500574' WHERE id='it_0039' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='18Y3600529' WHERE id='it_0228' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='WB82X01000' WHERE id='it_0167' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='WBA2Y01520' WHERE id='it_0179' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='REH8900952' WHERE id='it_0032' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='VUV4Z29494' WHERE id='it_0093' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='VUW7300018' WHERE id='it_0109' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='VUX7701168' WHERE id='it_0029' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='RPS1303424' WHERE id='it_0058' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='WB92Z00248' WHERE id='it_0052' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='WBA4401961' WHERE id='it_0142' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='WB82400163' WHERE id='it_0033' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='WB82X01162' WHERE id='it_0008' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='REH2710287' WHERE id='it_0133' AND (serial IS NULL OR serial='');
UPDATE rental_items SET serial='REH3110967' WHERE id='it_0003' AND (serial IS NULL OR serial='');

-- ---- rental_counters ----
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0150', '2026-01', 3895, 25632, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0253', '2026-01', 1863, 4663, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0242', '2026-01', 314, 7400, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0153', '2026-01', 47, 292, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0091', '2026-01', 50691, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0015', '2026-01', 23223, 41376, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0080', '2026-01', 4993, 2288, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0151', '2026-01', 36286, 39516, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0064', '2026-01', 372876, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0144', '2026-01', 9577, 767, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0081', '2026-01', 57749, 86352, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0079', '2026-01', 25055, 26408, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0060', '2026-01', 16848, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0260', '2026-01', 2750, 870, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0203', '2026-01', 49312, 5112, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0046', '2026-01', 59111, 76898, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0196', '2026-01', 10638, 37865, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0047', '2026-01', 180046, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0116', '2026-01', 162296, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0241', '2026-01', 1331, 5273, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0159', '2026-01', 15403, 15212, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0155', '2026-01', 2465, 6378, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0164', '2026-01', 12838, 30818, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0209', '2026-01', 11192, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0165', '2026-01', 64178, 62331, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0136', '2026-01', 2174, 17546, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0089', '2026-01', 265859, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0130', '2026-01', 37118, 5533, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0152', '2026-01', 6143, 13334, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0050', '2026-01', 67067, 75030, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0092', '2026-01', 10143, 37704, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0025', '2026-01', 20913, 45432, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0016', '2026-01', 110573, 137247, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0217', '2026-01', 24551, 18734, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0096', '2026-01', 232946, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0070', '2026-01', 6067, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0278', '2026-01', 132, 34, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0126', '2026-01', 41277, 12534, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0074', '2026-01', 38826, 114602, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0075', '2026-01', 16044, 59857, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0202', '2026-01', 4122, 9561, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0263', '2026-01', 1079, 3607, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0108', '2026-01', 115290, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0145', '2026-01', 72886, 16588, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0149', '2026-01', 8812, 16426, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0234', '2026-01', 50973, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0030', '2026-01', 41675, 29479, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0039', '2026-01', 9832, 52488, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0228', '2026-01', 1511, 2364, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0167', '2026-01', 15768, 59650, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0179', '2026-01', 9133, 29597, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0032', '2026-01', 59411, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0093', '2026-01', 2279, 4077, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0109', '2026-01', 5080, 16443, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0029', '2026-01', 11965, 41706, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0058', '2026-01', 27037, 23599, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0052', '2026-01', 55007, 34140, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0142', '2026-01', 87694, 29961, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0033', '2026-01', 10998, 29642, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0008', '2026-01', 5190, 29145, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0133', '2026-01', 488713, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0003', '2026-01', 3043, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0150', '2026-02', 3942, 26835, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0253', '2026-02', 1988, 5027, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0242', '2026-02', 1170, 7658, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0153', '2026-02', 47, 304, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0091', '2026-02', 53153, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0015', '2026-02', 24094, 42708, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0080', '2026-02', 6099, 2792, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0151', '2026-02', 36739, 39822, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0064', '2026-02', 381556, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0144', '2026-02', 9577, 767, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0081', '2026-02', 58039, 86923, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0079', '2026-02', 25441, 26609, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0060', '2026-02', 16872, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0260', '2026-02', 3536, 924, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0203', '2026-02', 52067, 5340, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0046', '2026-02', 59752, 78908, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0196', '2026-02', 11352, 38044, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0047', '2026-02', 187741, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0116', '2026-02', 162926, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0241', '2026-02', 1374, 5396, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0159', '2026-02', 15627, 15448, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0155', '2026-02', 2479, 6504, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0164', '2026-02', 12843, 30872, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0209', '2026-02', 11740, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0165', '2026-02', 64632, 63015, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0136', '2026-02', 2623, 20079, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0089', '2026-02', 267980, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0130', '2026-02', 37146, 5543, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0152', '2026-02', 6199, 13658, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0050', '2026-02', 67749, 76925, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0092', '2026-02', 10435, 38976, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0025', '2026-02', 21288, 49889, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0016', '2026-02', 112036, 145861, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0217', '2026-02', 24561, 18767, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0096', '2026-02', 238527, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0070', '2026-02', 6478, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0278', '2026-02', 252, 242, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0126', '2026-02', 42792, 12956, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0074', '2026-02', 39152, 115871, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0075', '2026-02', 16185, 60855, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0202', '2026-02', 4123, 9584, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0263', '2026-02', 1129, 4089, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0108', '2026-02', 118038, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0145', '2026-02', 73009, 17564, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0149', '2026-02', 8823, 16521, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0234', '2026-02', 54140, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0030', '2026-02', 43447, 30975, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0039', '2026-02', 9956, 53473, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0228', '2026-02', 1525, 2532, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0167', '2026-02', 15768, 59650, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0179', '2026-02', 9201, 30007, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0032', '2026-02', 59724, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0093', '2026-02', 2636, 5113, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0109', '2026-02', 5124, 16482, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0029', '2026-02', 12032, 41827, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0058', '2026-02', 28009, 24081, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0052', '2026-02', 57531, 35841, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0142', '2026-02', 90421, 30846, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0033', '2026-02', 11201, 30417, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0008', '2026-02', 5400, 30510, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0133', '2026-02', 498890, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0003', '2026-02', 3072, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0150', '2026-03', 3960, 28699, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0253', '2026-03', 2312, 5527, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0242', '2026-03', 1173, 8112, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0153', '2026-03', 67, 375, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0091', '2026-03', 56343, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0015', '2026-03', 24943, 44515, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0080', '2026-03', 7106, 3541, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0151', '2026-03', 38070, 40224, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0064', '2026-03', 392254, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0144', '2026-03', 9577, 767, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0081', '2026-03', 58681, 88071, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0079', '2026-03', 25815, 26990, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0060', '2026-03', 16872, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0260', '2026-03', 5982, 1030, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0203', '2026-03', 56298, 5776, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0046', '2026-03', 60118, 79829, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0196', '2026-03', 12830, 38845, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0047', '2026-03', 198339, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0116', '2026-03', 163940, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0241', '2026-03', 1594, 5705, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0159', '2026-03', 15985, 15723, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0155', '2026-03', 2499, 6576, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0164', '2026-03', 12870, 31046, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0209', '2026-03', 12165, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0165', '2026-03', 65051, 63748, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0136', '2026-03', 2824, 21705, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0089', '2026-03', 269693, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0130', '2026-03', 37219, 5604, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0152', '2026-03', 6494, 14153, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0050', '2026-03', 68466, 78336, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0092', '2026-03', 10616, 40561, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0025', '2026-03', 21785, 51061, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0016', '2026-03', 115258, 150562, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0217', '2026-03', 24583, 18806, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0096', '2026-03', 247009, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0070', '2026-03', 6892, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0278', '2026-03', 323, 573, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0126', '2026-03', 43136, 13022, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0074', '2026-03', 39640, 117911, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0075', '2026-03', 16382, 62395, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0202', '2026-03', 4125, 9647, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0263', '2026-03', 1242, 5420, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0108', '2026-03', 119983, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0145', '2026-03', 73147, 18641, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0149', '2026-03', 8829, 16526, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0234', '2026-03', 58906, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0030', '2026-03', 45897, 33051, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0039', '2026-03', 10249, 54014, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0228', '2026-03', 1534, 2712, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0167', '2026-03', 15768, 59650, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0179', '2026-03', 9327, 30384, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0032', '2026-03', 60125, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0093', '2026-03', 2636, 5113, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0109', '2026-03', 5132, 16535, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0029', '2026-03', 12117, 41976, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0058', '2026-03', 33136, 24367, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0052', '2026-03', 58894, 36337, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0142', '2026-03', 96961, 32377, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0033', '2026-03', 11484, 30936, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0008', '2026-03', 5630, 31938, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0133', '2026-03', 512821, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0003', '2026-03', 3089, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0150', '2026-04', 3978, 29850, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0253', '2026-04', 2459, 5966, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0242', '2026-04', 1181, 8166, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0153', '2026-04', 110, 397, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0091', '2026-04', 60497, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0015', '2026-04', 25648, 46169, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0080', '2026-04', 8126, 4332, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0151', '2026-04', 39409, 40640, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0064', '2026-04', 406076, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0144', '2026-04', 9577, 767, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0081', '2026-04', 59186, 89398, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0079', '2026-04', 26207, 27468, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0060', '2026-04', 16872, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0260', '2026-04', 7340, 1137, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0203', '2026-04', 60270, 6246, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0046', '2026-04', 60513, 86395, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0196', '2026-04', 13317, 39420, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0047', '2026-04', 208450, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0116', '2026-04', 166404, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0241', '2026-04', 1632, 5835, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0159', '2026-04', 16356, 16120, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0155', '2026-04', 2517, 6658, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0164', '2026-04', 12972, 31173, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0209', '2026-04', 12833, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0165', '2026-04', 65966, 64690, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0136', '2026-04', 3030, 23200, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0089', '2026-04', 271306, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0130', '2026-04', 37247, 5609, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0152', '2026-04', 6568, 14566, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0050', '2026-04', 69511, 79925, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0092', '2026-04', 10835, 42089, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0025', '2026-04', 22119, 51659, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0016', '2026-04', 117331, 153832, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0217', '2026-04', 24605, 18859, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0096', '2026-04', 256186, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0070', '2026-04', 7356, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0278', '2026-04', 450, 1167, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0126', '2026-04', 43155, 13055, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0074', '2026-04', 40097, 119340, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0075', '2026-04', 16530, 63549, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0202', '2026-04', 4125, 9653, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0263', '2026-04', 1473, 7372, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0108', '2026-04', 122527, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0145', '2026-04', 73309, 19635, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0149', '2026-04', 8883, 16646, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0234', '2026-04', 67497, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0030', '2026-04', 48066, 34805, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0039', '2026-04', 10363, 56426, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0228', '2026-04', 1632, 2787, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0167', '2026-04', 15768, 59650, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0179', '2026-04', 9419, 30999, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0032', '2026-04', 60693, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0093', '2026-04', 2636, 5113, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0109', '2026-04', 5142, 16555, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0029', '2026-04', 12263, 42108, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0058', '2026-04', 33667, 24492, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0052', '2026-04', 60326, 36935, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0142', '2026-04', 106649, 35531, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0033', '2026-04', 11815, 31659, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0008', '2026-04', 5860, 33398, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0133', '2026-04', 532212, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;
INSERT INTO rental_counters (item_id, ym, bw, color, source) VALUES ('it_0003', '2026-04', 3101, 0, 'xlsx-import') ON CONFLICT (item_id, ym) DO UPDATE SET bw=EXCLUDED.bw, color=EXCLUDED.color, source=EXCLUDED.source;

-- 통계: months=4, serial_updates=62, counters=248